[catalog.loupe]
name = "Loupe"
category = "misc"

[templates.loupe-flatpak]
input_path = "gtk.css"
output_path = "~/.var/app/org.gnome.Loupe/config/gtk-4.0/gtk.css"
requires_path = "~/.var/app/org.gnome.Loupe"
